language: ruby
rvm:
- 2.0.0
gemfile: TravisGemfile
install:
- bundle install
deploy:
  provider: heroku
  api_key: d3288def-bdfb-4865-945f-05c777eecf32
  app: hallinta
  on:
    repo: smooshi/hallinta
script:
- bundle exec rake db:migrate --trace
