require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DeviceInAgreementsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DeviceInAgreement. As you add validations to DeviceInAgreement, be sure to
  # adjust the attributes here as well.
  before :each do
    request.session[:user_id] = User.first.id
  end


  let(:valid_attributes) {
    {    "agreement_id" => 1,
    "device_id" => 1,
    "monthly_price" => 2,
    "total_price" =>2}
      }

  let(:invalid_attributes) {
    {    "agreement_id" => 1,
         "device_id" => 1
  }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeviceInAgreementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all device_in_agreements as @device_in_agreements" do
      device_in_agreement = DeviceInAgreement.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:device_in_agreements)).to eq([device_in_agreement])
    end
  end

  describe "GET #show" do
    it "assigns the requested device_in_agreement as @device_in_agreement" do
      device_in_agreement = DeviceInAgreement.create! valid_attributes
      get :show, {:id => device_in_agreement.to_param}, valid_session
      expect(assigns(:device_in_agreement)).to eq(device_in_agreement)
    end
  end

  describe "GET #new" do
    it "assigns a new device_in_agreement as @device_in_agreement" do
      get :new, {}, valid_session
      expect(assigns(:device_in_agreement)).to be_a_new(DeviceInAgreement)
    end
  end

  describe "GET #edit" do
    it "assigns the requested device_in_agreement as @device_in_agreement" do
      device_in_agreement = DeviceInAgreement.create! valid_attributes
      get :edit, {:id => device_in_agreement.to_param}, valid_session
      expect(assigns(:device_in_agreement)).to eq(device_in_agreement)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DeviceInAgreement" do
        expect {
          post :create, {:device_in_agreement => valid_attributes}, valid_session
        }.to change(DeviceInAgreement, :count).by(1)
      end

      it "assigns a newly created device_in_agreement as @device_in_agreement" do
        post :create, {:device_in_agreement => valid_attributes}, valid_session
        expect(assigns(:device_in_agreement)).to be_a(DeviceInAgreement)
        expect(assigns(:device_in_agreement)).to be_persisted
      end

      it "redirects to the created device_in_agreement" do
        post :create, {:device_in_agreement => valid_attributes}, valid_session
        expect(response).to redirect_to(DeviceInAgreement.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved device_in_agreement as @device_in_agreement" do
        post :create, {:device_in_agreement => invalid_attributes}, valid_session
        expect(assigns(:device_in_agreement)).to be_a_new(DeviceInAgreement)
      end

      it "re-renders the 'new' template" do
        post :create, {:device_in_agreement => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested device_in_agreement" do
        device_in_agreement = DeviceInAgreement.create! valid_attributes
        put :update, {:id => device_in_agreement.to_param, :device_in_agreement => new_attributes}, valid_session
        device_in_agreement.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested device_in_agreement as @device_in_agreement" do
        device_in_agreement = DeviceInAgreement.create! valid_attributes
        put :update, {:id => device_in_agreement.to_param, :device_in_agreement => valid_attributes}, valid_session
        expect(assigns(:device_in_agreement)).to eq(device_in_agreement)
      end

      it "redirects to the device_in_agreement" do
        device_in_agreement = DeviceInAgreement.create! valid_attributes
        put :update, {:id => device_in_agreement.to_param, :device_in_agreement => valid_attributes}, valid_session
        expect(response).to redirect_to(device_in_agreement)
      end
    end

    context "with invalid params" do
      it "assigns the device_in_agreement as @device_in_agreement" do
        device_in_agreement = DeviceInAgreement.create! valid_attributes
        put :update, {:id => device_in_agreement.to_param, :device_in_agreement => invalid_attributes}, valid_session
        expect(assigns(:device_in_agreement)).to eq(device_in_agreement)
      end

      it "re-renders the 'edit' template" do
        device_in_agreement = DeviceInAgreement.create! valid_attributes
        put :update, {:id => device_in_agreement.to_param, :device_in_agreement => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested device_in_agreement" do
      device_in_agreement = DeviceInAgreement.create! valid_attributes
      expect {
        delete :destroy, {:id => device_in_agreement.to_param}, valid_session
      }.to change(DeviceInAgreement, :count).by(-1)
    end

    it "redirects to the device_in_agreements list" do
      device_in_agreement = DeviceInAgreement.create! valid_attributes
      delete :destroy, {:id => device_in_agreement.to_param}, valid_session
      expect(response).to redirect_to(device_in_agreements_url)
    end
  end

end
