require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe OtherBillingInAgreementsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # OtherBillingInAgreement. As you add validations to OtherBillingInAgreement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OtherBillingInAgreementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all other_billing_in_agreements as @other_billing_in_agreements" do
      other_billing_in_agreement = OtherBillingInAgreement.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:other_billing_in_agreements)).to eq([other_billing_in_agreement])
    end
  end

  describe "GET #show" do
    it "assigns the requested other_billing_in_agreement as @other_billing_in_agreement" do
      other_billing_in_agreement = OtherBillingInAgreement.create! valid_attributes
      get :show, {:id => other_billing_in_agreement.to_param}, valid_session
      expect(assigns(:other_billing_in_agreement)).to eq(other_billing_in_agreement)
    end
  end

  describe "GET #new" do
    it "assigns a new other_billing_in_agreement as @other_billing_in_agreement" do
      get :new, {}, valid_session
      expect(assigns(:other_billing_in_agreement)).to be_a_new(OtherBillingInAgreement)
    end
  end

  describe "GET #edit" do
    it "assigns the requested other_billing_in_agreement as @other_billing_in_agreement" do
      other_billing_in_agreement = OtherBillingInAgreement.create! valid_attributes
      get :edit, {:id => other_billing_in_agreement.to_param}, valid_session
      expect(assigns(:other_billing_in_agreement)).to eq(other_billing_in_agreement)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new OtherBillingInAgreement" do
        expect {
          post :create, {:other_billing_in_agreement => valid_attributes}, valid_session
        }.to change(OtherBillingInAgreement, :count).by(1)
      end

      it "assigns a newly created other_billing_in_agreement as @other_billing_in_agreement" do
        post :create, {:other_billing_in_agreement => valid_attributes}, valid_session
        expect(assigns(:other_billing_in_agreement)).to be_a(OtherBillingInAgreement)
        expect(assigns(:other_billing_in_agreement)).to be_persisted
      end

      it "redirects to the created other_billing_in_agreement" do
        post :create, {:other_billing_in_agreement => valid_attributes}, valid_session
        expect(response).to redirect_to(OtherBillingInAgreement.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved other_billing_in_agreement as @other_billing_in_agreement" do
        post :create, {:other_billing_in_agreement => invalid_attributes}, valid_session
        expect(assigns(:other_billing_in_agreement)).to be_a_new(OtherBillingInAgreement)
      end

      it "re-renders the 'new' template" do
        post :create, {:other_billing_in_agreement => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested other_billing_in_agreement" do
        other_billing_in_agreement = OtherBillingInAgreement.create! valid_attributes
        put :update, {:id => other_billing_in_agreement.to_param, :other_billing_in_agreement => new_attributes}, valid_session
        other_billing_in_agreement.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested other_billing_in_agreement as @other_billing_in_agreement" do
        other_billing_in_agreement = OtherBillingInAgreement.create! valid_attributes
        put :update, {:id => other_billing_in_agreement.to_param, :other_billing_in_agreement => valid_attributes}, valid_session
        expect(assigns(:other_billing_in_agreement)).to eq(other_billing_in_agreement)
      end

      it "redirects to the other_billing_in_agreement" do
        other_billing_in_agreement = OtherBillingInAgreement.create! valid_attributes
        put :update, {:id => other_billing_in_agreement.to_param, :other_billing_in_agreement => valid_attributes}, valid_session
        expect(response).to redirect_to(other_billing_in_agreement)
      end
    end

    context "with invalid params" do
      it "assigns the other_billing_in_agreement as @other_billing_in_agreement" do
        other_billing_in_agreement = OtherBillingInAgreement.create! valid_attributes
        put :update, {:id => other_billing_in_agreement.to_param, :other_billing_in_agreement => invalid_attributes}, valid_session
        expect(assigns(:other_billing_in_agreement)).to eq(other_billing_in_agreement)
      end

      it "re-renders the 'edit' template" do
        other_billing_in_agreement = OtherBillingInAgreement.create! valid_attributes
        put :update, {:id => other_billing_in_agreement.to_param, :other_billing_in_agreement => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested other_billing_in_agreement" do
      other_billing_in_agreement = OtherBillingInAgreement.create! valid_attributes
      expect {
        delete :destroy, {:id => other_billing_in_agreement.to_param}, valid_session
      }.to change(OtherBillingInAgreement, :count).by(-1)
    end

    it "redirects to the other_billing_in_agreements list" do
      other_billing_in_agreement = OtherBillingInAgreement.create! valid_attributes
      delete :destroy, {:id => other_billing_in_agreement.to_param}, valid_session
      expect(response).to redirect_to(other_billing_in_agreements_url)
    end
  end

end
