require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RestaurantEvaluationsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RestaurantEvaluation. As you add validations to RestaurantEvaluation, be sure to
  # adjust the attributes here as well.

  before :each do
    request.session[:user_id] = User.first.id
  end

  let(:valid_attributes) {
    {
        "restaurant_id" => 1,
    "company_id" => 1,
    "user_id" => 1,
    "restaurant_evaluation_type_id" => 1,
    "value" => 1
    }
  }

  let(:invalid_attributes) {
    {
        "restaurant_id" => 1,
        "restaurant_evaluation_type_id" => 1,
        "value" => 1
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RestaurantEvaluationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all restaurant_evaluations as @restaurant_evaluations" do
      restaurant_evaluation = RestaurantEvaluation.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:restaurant_evaluations)).to eq([restaurant_evaluation])
    end
  end

  describe "GET #show" do
    it "assigns the requested restaurant_evaluation as @restaurant_evaluation" do
      restaurant_evaluation = RestaurantEvaluation.create! valid_attributes
      get :show, {:id => restaurant_evaluation.to_param}, valid_session
      expect(assigns(:restaurant_evaluation)).to eq(restaurant_evaluation)
    end
  end

  describe "GET #new" do
    it "assigns a new restaurant_evaluation as @restaurant_evaluation" do
      get :new, {}, valid_session
      expect(assigns(:restaurant_evaluation)).to be_a_new(RestaurantEvaluation)
    end
  end

  describe "GET #edit" do
    it "assigns the requested restaurant_evaluation as @restaurant_evaluation" do
      restaurant_evaluation = RestaurantEvaluation.create! valid_attributes
      get :edit, {:id => restaurant_evaluation.to_param}, valid_session
      expect(assigns(:restaurant_evaluation)).to eq(restaurant_evaluation)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RestaurantEvaluation" do
        expect {
          post :create, {:restaurant_evaluation => valid_attributes}, valid_session
        }.to change(RestaurantEvaluation, :count).by(1)
      end

      it "assigns a newly created restaurant_evaluation as @restaurant_evaluation" do
        post :create, {:restaurant_evaluation => valid_attributes}, valid_session
        expect(assigns(:restaurant_evaluation)).to be_a(RestaurantEvaluation)
        expect(assigns(:restaurant_evaluation)).to be_persisted
      end

      it "redirects to the created restaurant_evaluation" do
        post :create, {:restaurant_evaluation => valid_attributes}, valid_session
        expect(response).to redirect_to(RestaurantEvaluation.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved restaurant_evaluation as @restaurant_evaluation" do
        post :create, {:restaurant_evaluation => invalid_attributes}, valid_session
        expect(assigns(:restaurant_evaluation)).to be_a_new(RestaurantEvaluation)
      end

      it "re-renders the 'new' template" do
        post :create, {:restaurant_evaluation => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested restaurant_evaluation" do
        restaurant_evaluation = RestaurantEvaluation.create! valid_attributes
        put :update, {:id => restaurant_evaluation.to_param, :restaurant_evaluation => new_attributes}, valid_session
        restaurant_evaluation.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested restaurant_evaluation as @restaurant_evaluation" do
        restaurant_evaluation = RestaurantEvaluation.create! valid_attributes
        put :update, {:id => restaurant_evaluation.to_param, :restaurant_evaluation => valid_attributes}, valid_session
        expect(assigns(:restaurant_evaluation)).to eq(restaurant_evaluation)
      end

      it "redirects to the restaurant_evaluation" do
        restaurant_evaluation = RestaurantEvaluation.create! valid_attributes
        put :update, {:id => restaurant_evaluation.to_param, :restaurant_evaluation => valid_attributes}, valid_session
        expect(response).to redirect_to(restaurant_evaluation)
      end
    end

    context "with invalid params" do
      it "assigns the restaurant_evaluation as @restaurant_evaluation" do
        restaurant_evaluation = RestaurantEvaluation.create! valid_attributes
        put :update, {:id => restaurant_evaluation.to_param, :restaurant_evaluation => invalid_attributes}, valid_session
        expect(assigns(:restaurant_evaluation)).to eq(restaurant_evaluation)
      end

      it "re-renders the 'edit' template" do
        restaurant_evaluation = RestaurantEvaluation.create! valid_attributes
        put :update, {:id => restaurant_evaluation.to_param, :restaurant_evaluation => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested restaurant_evaluation" do
      restaurant_evaluation = RestaurantEvaluation.create! valid_attributes
      expect {
        delete :destroy, {:id => restaurant_evaluation.to_param}, valid_session
      }.to change(RestaurantEvaluation, :count).by(-1)
    end

    it "redirects to the restaurant_evaluations list" do
      restaurant_evaluation = RestaurantEvaluation.create! valid_attributes
      delete :destroy, {:id => restaurant_evaluation.to_param}, valid_session
      expect(response).to redirect_to(restaurant_evaluations_url)
    end
  end

end
