require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SoftwareInAgreementsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # SoftwareInAgreement. As you add validations to SoftwareInAgreement, be sure to
  # adjust the attributes here as well.
  before :each do
    request.session[:user_id] = User.first.id
  end
  let(:valid_attributes) {
    {    "agreement_id"=> 1,
    "software_id" => 1,
    "monthly_price" => 2}
  }

  let(:invalid_attributes) {
    {    "agreement_id"=> 1,
         "software_id" => 1}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SoftwareInAgreementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all software_in_agreements as @software_in_agreements" do
      software_in_agreement = SoftwareInAgreement.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:software_in_agreements)).to eq([software_in_agreement])
    end
  end

  describe "GET #show" do
    it "assigns the requested software_in_agreement as @software_in_agreement" do
      software_in_agreement = SoftwareInAgreement.create! valid_attributes
      get :show, {:id => software_in_agreement.to_param}, valid_session
      expect(assigns(:software_in_agreement)).to eq(software_in_agreement)
    end
  end

  describe "GET #new" do
    it "assigns a new software_in_agreement as @software_in_agreement" do
      get :new, {}, valid_session
      expect(assigns(:software_in_agreement)).to be_a_new(SoftwareInAgreement)
    end
  end

  describe "GET #edit" do
    it "assigns the requested software_in_agreement as @software_in_agreement" do
      software_in_agreement = SoftwareInAgreement.create! valid_attributes
      get :edit, {:id => software_in_agreement.to_param}, valid_session
      expect(assigns(:software_in_agreement)).to eq(software_in_agreement)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SoftwareInAgreement" do
        expect {
          post :create, {:software_in_agreement => valid_attributes}, valid_session
        }.to change(SoftwareInAgreement, :count).by(1)
      end

      it "assigns a newly created software_in_agreement as @software_in_agreement" do
        post :create, {:software_in_agreement => valid_attributes}, valid_session
        expect(assigns(:software_in_agreement)).to be_a(SoftwareInAgreement)
        expect(assigns(:software_in_agreement)).to be_persisted
      end

      it "redirects to the created software_in_agreement" do
        post :create, {:software_in_agreement => valid_attributes}, valid_session
        expect(response).to redirect_to(SoftwareInAgreement.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved software_in_agreement as @software_in_agreement" do
        post :create, {:software_in_agreement => invalid_attributes}, valid_session
        expect(assigns(:software_in_agreement)).to be_a_new(SoftwareInAgreement)
      end

      it "re-renders the 'new' template" do
        post :create, {:software_in_agreement => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested software_in_agreement" do
        software_in_agreement = SoftwareInAgreement.create! valid_attributes
        put :update, {:id => software_in_agreement.to_param, :software_in_agreement => new_attributes}, valid_session
        software_in_agreement.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested software_in_agreement as @software_in_agreement" do
        software_in_agreement = SoftwareInAgreement.create! valid_attributes
        put :update, {:id => software_in_agreement.to_param, :software_in_agreement => valid_attributes}, valid_session
        expect(assigns(:software_in_agreement)).to eq(software_in_agreement)
      end

      it "redirects to the software_in_agreement" do
        software_in_agreement = SoftwareInAgreement.create! valid_attributes
        put :update, {:id => software_in_agreement.to_param, :software_in_agreement => valid_attributes}, valid_session
        expect(response).to redirect_to(software_in_agreement)
      end
    end

    context "with invalid params" do
      it "assigns the software_in_agreement as @software_in_agreement" do
        software_in_agreement = SoftwareInAgreement.create! valid_attributes
        put :update, {:id => software_in_agreement.to_param, :software_in_agreement => invalid_attributes}, valid_session
        expect(assigns(:software_in_agreement)).to eq(software_in_agreement)
      end

      it "re-renders the 'edit' template" do
        software_in_agreement = SoftwareInAgreement.create! valid_attributes
        put :update, {:id => software_in_agreement.to_param, :software_in_agreement => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested software_in_agreement" do
      software_in_agreement = SoftwareInAgreement.create! valid_attributes
      expect {
        delete :destroy, {:id => software_in_agreement.to_param}, valid_session
      }.to change(SoftwareInAgreement, :count).by(-1)
    end

    it "redirects to the software_in_agreements list" do
      software_in_agreement = SoftwareInAgreement.create! valid_attributes
      delete :destroy, {:id => software_in_agreement.to_param}, valid_session
      expect(response).to redirect_to(software_in_agreements_url)
    end
  end

end
